from torch import nn
from torch.functional import F

FIRST_LAYER_KERNEL_SIZE = 3
FIRST_LAYER_STRIDE = 2
FIRST_LAYER_OUT = 32

SECOND_LAYER_KERNEL_SIZE = 3
SECOND_LAYER_STRIDE = 1
SECOND_LAYER_OUT = 32

THIRD_LAYER_KERNEL_SIZE = 3
THIRD_LAYER_STRIDE = 1
THIRD_LAYER_OUT = 32

